#!/usr/bin/expect -f

set timeout -1
spawn $env(SHELL)
match_max 100000
expect "# "
sleep 2
send -- "apt-get -t testing install -y hostapd\r"
expect "answer No to the question below."
sleep 2
send -- "\r"
expect "Do you want to upgrade glibc now?"
sleep 2
send -- "\r"
expect "Restart services during package upgrades without asking?"
sleep 2
send -- "	\r"
expect "[default=N\] ? "
sleep 2
send -- "\r"
